# Generated by Django 2.1.7 on 2019-04-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sex', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trestbps', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chol', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fbs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('restecg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('thalach', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exang', models.DecimalField(decimal_places=2, max_digits=5)),
                ('oldpeak', models.DecimalField(decimal_places=2, max_digits=5)),
                ('slope', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ca', models.DecimalField(decimal_places=2, max_digits=5)),
                ('thai', models.DecimalField(decimal_places=2, max_digits=5)),
                ('num', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
