# Generated by Django 2.2 on 2019-04-13 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20190411_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='thai',
            new_name='thal',
        ),
    ]
