# Generated by Django 2.2 on 2019-04-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20190413_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='sex',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
